routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::get('/', 'HomeController@index')
    ->name('home')
    ->middleware('auth');
Route::resource('fee', 'FeeController')
    ->middleware('auth');
Route::resource('exemption-type', 'ExemptionTypeController')
    ->middleware('auth');
Route::resource('exemption-source', 'ExemptionSourceController')
    ->middleware('auth');
Route::resource('user', 'UserController')
    ->middleware('auth');
Route::resource('exemption', 'ExemptionController')
    ->middleware('auth');
Route::get('report', 'ReportController@index')
    ->name('report.index')
    ->middleware('auth');
Route::get('report/csv', 'ReportController@getCSV')
    ->name('report.csv')
    ->middleware('auth');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

app/Http/Controllers/ExemptionTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\ExemptionType;

class ExemptionTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list = ExemptionType::orderBy('title', 'asc')
            ->get();

        return view('exemption-type.index', [
            'list' => $list,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('exemption-type.form', [
            'exemptionType' => new ExemptionType(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formData = $request->validate([
            'title' => 'required|string|max:20',
        ]);

        ExemptionType::create($formData);

        return redirect()->to(route('exemption-type.index'))
            ->with('success', __('Yeni muafiyet türü yaratıldı'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ExemptionType  $exemptionType
     * @return \Illuminate\Http\Response
     */
    public function show(ExemptionType $exemptionType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ExemptionType  $exemptionType
     * @return \Illuminate\Http\Response
     */
    public function edit(ExemptionType $exemptionType)
    {
        return view('exemption-type.form', [
            'exemptionType' => $exemptionType,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ExemptionType  $exemptionType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ExemptionType $exemptionType)
    {
        $formData = $request->validate([
            'title' => 'required|string|max:20',
        ]);

        $exemptionType->fill($formData);
        $exemptionType->save();

        return redirect()->to(route('exemption-type.index'))
            ->with('success', __('Muafiyet türü kaydedildi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ExemptionType  $exemptionType
     * @return \Illuminate\Http\Response
     */
    public function destroy(ExemptionType $exemptionType)
    {
        $exemptionType->delete();

        return redirect()->back()
            ->with('success', __('Muafiyet türü silindi'));
    }
}

resources/views/exemption-type/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h3 class="mb-5">{{ __('Muafiyet türü') }}</h3>

  @include('partials.notifications')

  <form
    method="post"
    @if($exemptionType->id)
      action="{{ route('exemption-type.update', $exemptionType->id) }}"
    @else
      action="{{ route('exemption-type.store') }}"
    @endif
  >
    @csrf

    @if($exemptionType->id)
      <input type="hidden" name="_method" value="put">
    @endif

    <div class="form-group">
      <label for="title">{{ __('Muafiyet türü') }}</label>
      <input
        type="text"
        name="title"
        id="title"
        class="form-control"
        required
        value="{{ old('title') ?: $exemptionType->title }}"
        maxlength="20"
      >
    </div>

    <div>
      <button type="submit" class="btn btn-primary btn-block">{{ __('Kaydet') }}</button>
    </div>
  </form>
</div>
@endsection

resources/views/exemption-type/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row mb-5">
    <div class="col-12 col-sm-8 text-center text-sm-left">
      <h3>{{ __('Muafiyet Türleri') }}</h3>
    </div>
    <div class="col-12 col-sm-4 text-center text-sm-right">
      <a class="btn btn-outline-info" href="{{ route('exemption-type.create') }}">
        {{ __('Yeni Muafiyet Türü') }}
      </a>
    </div>
  </div>

  @include('partials.notifications')

  <table class="table table-responsive-xs table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>{{ __('Muafiyet türü') }}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($list as $item)
      <tr>
        <td>{{ $item->id }}</td>
        <td>{{ $item->title }}</td>
        <td class="text-right">
          <a class="btn btn-outline-info" href="{{ route('exemption-type.edit', $item->id) }}">{{ __('Düzenle') }}</a>
          <form class="d-inline" action="{{ route('exemption-type.destroy', $item->id) }}" method="post">
            @csrf
            <input type="hidden" name="_method" value="delete">
            <button
              type="submit"
              class="btn btn-outline-danger"
            >{{ __('Sil') }}</button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endsection