routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::get('/', 'HomeController@index')
    ->name('home')
    ->middleware('auth');
Route::resource('fee', 'FeeController')
    ->middleware('auth');
Route::resource('exemption-type', 'ExemptionTypeController')
    ->middleware('auth');
Route::resource('exemption-source', 'ExemptionSourceController')
    ->middleware('auth');
Route::resource('user', 'UserController')
    ->middleware('auth');
Route::resource('exemption', 'ExemptionController')
    ->middleware('auth');
Route::get('report', 'ReportController@index')
    ->name('report.index')
    ->middleware('auth');
Route::get('report/csv', 'ReportController@getCSV')
    ->name('report.csv')
    ->middleware('auth');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'code',
        'last_name',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function exemptions()
    {
        return $this->hasMany(Exemption::class, 'user_id');
    }

    public function currentExemption()
    {
        return $this->hasOne(Exemption::class, 'user_id')
            ->whereNull('ends_at');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list = User::orderBy('name', 'asc')
            ->get();

        return view('user.index', [
            'list' => $list,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.form', [
            'user' => new User(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formData = $request->validate([
            'name' => 'required|string|max:40',
            'last_name' => 'required|string|max:40',
            'code' => 'required|integer|min:0|max:999999|unique:users,code',
        ]);

        User::create($formData);

        return redirect()->to(route('user.index'))
            ->with('success', __('Yeni üye yaratıldı'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('user.form', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $formData = $request->validate([
            'name' => 'required|string|max:40',
            'last_name' => 'required|string|max:40',
            'code' => [
                'required',
                'integer',
                'min:0',
                'max:999999',
                Rule::unique('users')->ignore($user->id),
            ],
        ]);

        $user->fill($formData);
        $user->save();

        return redirect()->to(route('user.index'))
            ->with('success', __('Üye kaydedildi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->back()
            ->with('success', __('Kullanıcı silindi'));
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h3 class="mb-5">{{ __('Üye') }}</h3>

  @include('partials.notifications')

  <form
    method="post"
    @if($user->id)
      action="{{ route('user.update', $user->id) }}"
    @else
      action="{{ route('user.store') }}"
    @endif
  >
    @csrf

    @if($user->id)
      <input type="hidden" name="_method" value="put">
    @endif

    <div class="form-group">
      <label for="code">{{ __('Sicil No.') }}</label>
      <input
        type="number"
        name="code"
        id="code"
        class="form-control form-control-sm"
        required
        value="{{ old('code') ?: $user->code }}"
        max="999999"
        min="1"
        step="1"
      >
    </div>

    <div class="form-group">
      <label for="name">{{ __('Ad') }}</label>
      <input
        type="text"
        name="name"
        id="name"
        class="form-control form-control-sm"
        required
        value="{{ old('name') ?: $user->name }}"
        maxlength="40"
      >
    </div>

    <div class="form-group">
      <label for="last_name">{{ __('Soyadı') }}</label>
      <input
        type="text"
        name="last_name"
        id="last_name"
        class="form-control form-control-sm"
        required
        value="{{ old('last_name') ?: $user->last_name }}"
        maxlength="40"
      >
    </div>

    <div>
      <button type="submit" class="btn btn-primary btn-block">{{ __('Kaydet') }}</button>
    </div>
  </form>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row mb-5">
    <div class="col-12 col-sm-8 text-center text-sm-left">
      <h3>{{ __('Üyeler') }}</h3>
    </div>
    <div class="col-12 col-sm-4 text-center text-sm-right">
      <a class="btn btn-outline-info" href="{{ route('user.create') }}">
        {{ __('Yeni Üye') }}
      </a>
    </div>
  </div>

  @include('partials.notifications')

  <table class="table table-responsive-xs table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>{{ __('Sicil No.') }}</th>
        <th>{{ __('İsim') }}</th>
        <th>{{ __('Soyisim') }}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($list as $item)
      <tr>
        <td>{{ $item->id }}</td>
        <td>{{ $item->code }}</td>
        <td>{{ $item->name }}</td>
        <td>{{ $item->last_name }}</td>
        <td class="text-right">
          <a
            class="btn btn-outline-secondary"
            href="{{ route('exemption.index', ['code' => $item->code]) }}"
          >{{ __('Muafiyetler') }}</a>
          <a class="btn btn-outline-info" href="{{ route('user.edit', $item->id) }}">{{ __('Düzenle') }}</a>
          <form class="d-inline" action="{{ route('user.destroy', $item->id) }}" method="post">
            @csrf
            <input type="hidden" name="_method" value="delete">
            <button
              type="submit"
              class="btn btn-outline-danger"
            >{{ __('Sil') }}</button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endsection