routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::get('/', 'HomeController@index')
    ->name('home')
    ->middleware('auth');
Route::resource('fee', 'FeeController')
    ->middleware('auth');
Route::resource('exemption-type', 'ExemptionTypeController')
    ->middleware('auth');
Route::resource('exemption-source', 'ExemptionSourceController')
    ->middleware('auth');
Route::resource('user', 'UserController')
    ->middleware('auth');
Route::resource('exemption', 'ExemptionController')
    ->middleware('auth');
Route::get('report', 'ReportController@index')
    ->name('report.index')
    ->middleware('auth');
Route::get('report/csv', 'ReportController@getCSV')
    ->name('report.csv')
    ->middleware('auth');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

app/Models/Exemption.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Exemption extends Model
{
    protected $fillable = [
        'exemption_type_id',
        'exemption_source_id',
        'user_id',
        'starts_at',
        'ends_at',
        'exemption_source_at',
        'exemption_info',
        'substracted_month_count',
    ];

    public $casts = [
        'starts_at' => 'date',
        'ends_at' => 'date',
        'exemption_source_at' => 'date',
        'substracted_month_count' => 'int',
    ];

    public $appends = [
        'month_count',
        'exempted_month_count',
        'fee_to_substract',
    ];

    public function exemptionType()
    {
        return $this->belongsTo(ExemptionType::class, 'exemption_type_id');
    }

    public function exemptionSource()
    {
        return $this->belongsTo(ExemptionSource::class, 'exemption_source_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getMonthCountAttribute()
    {
        $endsAt = $this->ends_at ?: now();
        $dayDiff = $endsAt->diffInDays($this->starts_at);
        $daysLeft = $dayDiff % 30;

        if ($daysLeft > 10) {
            return ceil($dayDiff / 30);
        }

        return floor($dayDiff / 30);
    }

    public function getExemptedMonthCountAttribute()
    {
        return $this->month_count - $this->substracted_month_count;
    }

    public function getFeeToSubstractAttribute(): float
    {
        $model = $this;

        if (empty($model->ends_at)) {
            $fee = Fee::whereNull('ends_at')->first();
        } else {
            $fee = Fee::where('starts_at', '<=', $this->starts_at)
                ->where(function ($query) use ($model) {
                    $query->whereDate('ends_at', '>=', $model->ends_at)
                        ->orWhereNull('ends_at');
                })
                ->first();
        }

        if (!empty($fee)) {
            return $this->exempted_month_count * $fee->amount;
        }

        $feeStart = Fee::where('starts_at', '<=', $this->starts_at)
            ->orderBy('starts_at', 'desc')
            ->first();

        if (empty($feeStart)) {
            // There is no fee for this date
            $feeStart = Fee::where('starts_at', '>=', $this->starts_at)
                ->orderBy('starts_at', 'asc')
                ->first();
        }

        $daysFirst = $this->starts_at->diffInDays($feeStart->ends_at);

        if ($daysFirst % 30 > 10) {
            $amountFirst = ceil($daysFirst / 30) * $feeStart->amount;
        } else {
            $amountFirst = floor($daysFirst / 30) * $feeStart->amount;
        }

        $feeEnd = Fee::where('starts_at', '>=', $this->starts_at)
            ->orderBy('starts_at', 'asc')
            ->first();

        if (empty($feeEnd)) {
            // There is no fee for this date
            $feeEnd = Fee::where('starts_at', '<=', $this->starts_at)
            ->orderBy('starts_at', 'desc')
            ->first();
        }

        $daysLast = $this->ends_at->diffInDays($feeEnd->starts_at);

        if ($daysLast % 30 > 10) {
            $amountLast = ceil($daysLast / 30) * $feeEnd->amount;
        } else {
            $amountLast = floor($daysLast / 30) * $feeEnd->amount;
        }

        $amount = $amountFirst + $amountLast;

        if (!empty($this->substracted_month_count)) {
            $amount -= $this->substracted_month_count * $feeStart->amount;
        }

        return $amount;
    }
}

app/Models/ExemptionType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ExemptionType extends Model
{
    protected $fillable = [
        'title',
    ];
}

app/Http/Controllers/ExemptionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Exemption;
use App\Models\ExemptionSource;
use App\Models\ExemptionType;
use App\Models\User;

class ExemptionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filters = $request->validate([
            'code' => 'int|nullable|sometimes',
            'name' => 'string|nullable|sometimes',
            'last_name' => 'string|nullable|sometimes',
        ]);

        $user = null;
        $currentExemption = null;
        $totalSubstractedMonthCount = 0;
        $totalMonthCount = 0;
        $totalExemptedMonthCount = 0;
        $totalFeeToSubstract = 0;

        if (empty($filters)) {
            $list = collect();
        } else {
            $user = new User();

            $query = Exemption::join('users AS u', 'u.id', '=', 'exemptions.user_id')
                ->select('exemptions.*');

            if (array_key_exists('code', $filters)) {
                $user = User::where('code', $filters['code'])
                    ->firstOrFail();

                $query->where('u.code', $user->code);
            }


            $list = $query
                ->with([
                    'user',
                    'exemptionType',
                    'exemptionSource',
                ])
                ->orderBy('exemptions.starts_at', 'desc')
                ->get();

            foreach ($list as $item) {
                if (!empty($item->ends_at)) {
                    $totalSubstractedMonthCount += $item->substracted_month_count;
                    $totalMonthCount += $item->month_count;
                    $totalExemptedMonthCount += $item->exempted_month_count;
                    $totalFeeToSubstract += $item->fee_to_substract;
                }
            }

            if ($list->count() and is_null($list->first()->ends_at)) {
                $currentExemption = $list->first();
            }
        }

        return view('exemption.index', [
            'list' => $list,
            'user' => $user,
            'currentExemption' => $currentExemption,
            'totalSubstractedMonthCount' => $totalSubstractedMonthCount,
            'totalExemptedMonthCount' => $totalExemptedMonthCount,
            'totalFeeToSubstract' => $totalFeeToSubstract,
            'totalMonthCount' => $totalMonthCount,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $form = $request->validate([
            'user_id' => 'required|integer',
        ]);

        $user = User::findOrFail($form['user_id']);
        $exemption = new Exemption();

        $typeList = ExemptionType::all();
        $sourceList = ExemptionSource::all();

        return view('exemption.form', [
            'user' => $user,
            'exemption' => $exemption,
            'typeList' => $typeList,
            'sourceList' => $sourceList,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formData = $request->validate([
            'starts_at' => 'required|date_format:Y-m-d',
            'ends_at' => 'date_format:Y-m-d|nullable',
            'user_id' => 'required|exists:users,id',
            'exemption_type_id' => 'required|exists:exemption_types,id',
            'exemption_source_id' => 'required|exists:exemption_sources,id',
            'exemption_source_at' => 'required|date_format:Y-m-d',
            'exemption_info' => 'required|string',
            'substracted_month_count' => 'required|int|min:0|max:999',
        ]);

        $exemption = Exemption::create($formData);

        return redirect()->to(route('exemption.index', [
            'code' => $exemption->user->code,
        ]))->with('success', __('Yeni muafiyet yaratıldı'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Exemption  $exemption
     * @return \Illuminate\Http\Response
     */
    public function show(Exemption $exemption)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Exemption  $exemption
     * @return \Illuminate\Http\Response
     */
    public function edit(Exemption $exemption)
    {
        $user = $exemption->user;

        $typeList = ExemptionType::all();
        $sourceList = ExemptionSource::all();

        return view('exemption.form', [
            'user' => $user,
            'exemption' => $exemption,
            'typeList' => $typeList,
            'sourceList' => $sourceList,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Exemption  $exemption
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exemption $exemption)
    {
        $formData = $request->validate([
            'starts_at' => 'required|date_format:Y-m-d',
            'ends_at' => 'date_format:Y-m-d|nullable',
            'exemption_type_id' => 'required|exists:exemption_types,id',
            'exemption_source_id' => 'required|exists:exemption_sources,id',
            'exemption_source_at' => 'required|date_format:Y-m-d',
            'exemption_info' => 'required|string',
            'substracted_month_count' => 'required|int|min:0|max:999',
        ]);

        $exemption->fill($formData);
        $exemption->save();

        return redirect()->to(route('exemption.index', [
            'code' => $exemption->user->code,
        ]))->with('success', __('Muafiyet güncellendi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Exemption  $exemption
     * @return \Illuminate\Http\Response
     */
    public function destroy(Exemption $exemption)
    {
        $exemption->delete();

        return redirect()->back()
            ->with('success', __('Muafiyet silindi'));
    }
}

resources/views/exemption/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h3 class="mb-5">
    {{ __('Muafiyet Ekle') }}
    - <strong class="text-danger">
      {{ $user->name }} {{ $user->last_name }}
    </strong>
  </h3>

  @include('partials.notifications')

  <form
    method="post"
    @if($exemption->id)
      action="{{ route('exemption.update', $exemption->id) }}"
    @else
      action="{{ route('exemption.store') }}"
    @endif
  >
    @csrf

    @if($exemption->id)
      <input type="hidden" name="_method" value="put">
    @else
      <input type="hidden" name="user_id" value="{{ $user->id }}">
    @endif

    <div class="row">
      <div class="col-12 col-md-6">
        <div class="form-group">
          <label for="user">{{ __('Üye') }}</label>
          <input
            name="user"
            id="user"
            class="form-control form-control-sm"
            disabled
            value="{{ $user->code }} - {{ $user->name }} {{ $user->last_name }}"
          >
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="form-group">
          <label for="exemption_type_id">{{ __('Tür') }}</label>
          <select
            name="exemption_type_id"
            id="exemption_type_id"
            class="form-control form-control-sm"
            required
          >
            <option></option>
            @foreach($typeList as $item)
              <option
                value="{{ $item->id }}"
                @if((int)(old('exemption_type_id') ?: $exemption->exemption_type_id) === $item->id)
                  selected
                @endif
              >{{ $item->title }}</option>
            @endforeach
          </select>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6">
        <div class="form-group">
          <label for="starts_at">{{ __('Başlangıç tarihi') }}</label>
          <input
            type="date"
            name="starts_at"
            id="starts_at"
            class="form-control form-control-sm"
            required
            value="{{ old('starts_at') ?: (!empty($exemption->starts_at) ? $exemption->starts_at->format('Y-m-d') : '') }}"
          >
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="form-group">
          <label for="ends_at">{{ __('Bitiş tarihi') }}</label>
          <input
            type="date"
            name="ends_at"
            id="ends_at"
            class="form-control form-control-sm"
            value="{{ old('ends_at') ?: (!empty($exemption->ends_at) ? $exemption->ends_at->format('Y-m-d') : '') }}"
          >
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6">
        <div class="form-group">
          <label for="exemption_source_id">{{ __('Bilgi kaynağı') }}</label>
          <select
            name="exemption_source_id"
            id="exemption_source_id"
            class="form-control form-control-sm"
            required
          >
            <option></option>
            @foreach($sourceList as $item)
              <option
                value="{{ $item->id }}"
                @if((int)(old('exemption_source_id') ?: $exemption->exemption_source_id) === $item->id)
                  selected
                @endif
              >{{ $item->title }}</option>
            @endforeach
          </select>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="form-group">
          <label for="exemption_source_at">{{ __('Belge tarihi') }}</label>
          <input
            type="date"
            name="exemption_source_at"
            id="exemption_source_at"
            class="form-control form-control-sm"
            required
            value="{{ old('exemption_source_at') ?: (!empty($exemption->exemption_source_at) ? $exemption->exemption_source_at->format('Y-m-d') : '') }}"
          >
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="name">{{ __('Belge açıklaması') }}</label>
      <textarea
        name="exemption_info"
        id="exemption_info"
        class="form-control form-control-sm"
        required
        maxlength="300"
      >{{ old('exemption_info') ?: $exemption->exemption_info }}</textarea>
    </div>

    <div class="form-group">
      <label for="substracted_month_count">{{ __('Düşülen ay sayısı') }}</label>
      <input
        type="number"
        name="substracted_month_count"
        id="substracted_month_count"
        class="form-control form-control-sm"
        required
        value="{{ old('substracted_month_count') ?: $exemption->substracted_month_count ?: 0 }}"
        min="0"
        max="999"
        step="1"
      >
    </div>

    <div>
      <button type="submit" class="btn btn-primary btn-block">{{ __('Kaydet') }}</button>
    </div>
  </form>
</div>
@endsection

resources/views/exemption/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="row mb-5">
    <div class="col-12 col-sm-8 text-center text-sm-left">
      <h3>
        {{ __('Muafiyet Kayıtları') }}
        @if(!empty($user) and $user->id)
          - <strong class="text-danger">
            {{ $user->name }} {{ $user->last_name }}
          </strong>
        @endif
      </h3>

      @if(!empty($currentExemption))
        {{ __('Güncel muafiyet:') }}
        <span class="text-danger">
          {{ $currentExemption->exemptionType->title }}
        </span>
      @endif
    </div>
    <div class="col-12 col-sm-4 text-center text-sm-right">
      @if(!empty($user) and $user->id)
        <a
          class="btn btn-outline-info"
          href="{{ route('exemption.create', ['user_id' => $user->id]) }}"
        >{{ __('Yeni Muafiyet Ekle') }}</a>
      @endif
    </div>
  </div>

  <form action="{{ route('exemption.index') }}" method="get" class="mb-3">
    <div class="form-group row">
      <label class="col-sm-2 col-lg-1 col-form-label" for="code">
        {{ __('Sicil No.') }}
      </label>
      <div class="col-sm-10 col-md-6 col-lg-4">
        <input
          class="form-control input-sm"
          type="number"
          min="1"
          max="999999"
          step="1"
          name="code"
          id="code"
          value="{{ request('code') }}"
        >
      </div>
    </div>

    <button type="submit" class="btn btn-outline-secondary">
      {{ __('Ara') }}
    </button>
  </form>

  @include('partials.notifications')

  <table class="table table-responsive-xs table-striped">
    <thead>
      <tr>
        <th>{{ __('Sicil No.') }}</th>
        <th>{{ __('Tür') }}</th>
        <th>{{ __('Başlama tarihi') }}</th>
        <th>{{ __('Bitiş tarihi') }}</th>
        <th>{{ __('Bilgi kaynağı') }}</th>
        <th>{{ __('Belge tarihi') }}</th>
        <th>{{ __('Belge Açıklaması') }}</th>
        <th>{{ __('Düşülen ay sayısı') }}</th>
        <th>{{ __('Ay sayısı') }}</th>
        <th>{{ __('Muaf ay sayısı') }}</th>
        <th>{{ __('Eksiltilecek tutar') }}</th>
        <th></th>
      </tr>
    </thead>
    @if($list->count())
      <tfoot class="font-weight-bold">
        <tr>
          <td colspan="7" class="text-right">
            {{ __('Toplam') }}
          </td>
          <td class="text-right">{{ $totalSubstractedMonthCount }}</td>
          <td class="text-right">{{ $totalMonthCount }}</td>
          <td class="text-right">{{ $totalExemptedMonthCount }}</td>
          <td class="text-right">{{ $totalFeeToSubstract }} TL</td>
        </tr>
      </tfoot>
    @endif
    <tbody>
      @foreach($list as $item)
      <tr>
        <td>{{ $item->user->code }}</td>
        <td>{{ $item->exemptionType->title }}</td>
        <td>{{ $item->starts_at->format('d.m.Y') }}</td>
        <td>
          @if(!empty($item->ends_at))
            {{ $item->ends_at->format('d.m.Y') }}
          @else
            <span class="text-muted">{{ __('girilmemiş') }}</span>
          @endif
        </td>
        <td>{{ $item->exemptionSource->title }}</td>
        <td>{{ $item->exemption_source_at->format('d.m.Y') }}</td>
        <td>{{ $item->exemption_info }}</td>
        <td class="text-right">{{ $item->substracted_month_count }}</td>
        <td class="text-right">{{ $item->month_count }}</td>
        <td class="text-right">{{ $item->exempted_month_count }}</td>
        <td class="text-right">{{ $item->fee_to_substract }} TL</td>
        <td class="text-right">
          <a class="btn btn-outline-info" href="{{ route('exemption.edit', $item->id) }}">{{ __('Düzenle') }}</a>
          <form class="d-inline" action="{{ route('exemption.destroy', $item->id) }}" method="post">
            @csrf
            <input type="hidden" name="_method" value="delete">
            <button
              type="submit"
              class="btn btn-outline-danger"
            >{{ __('Sil') }}</button>
          </form>
        </td>
      </tr>
      @endforeach
      @if (!empty($user->id) and !$list->count())
        <tr>
          <td class="text-center text-muted" colspan="12">
            {{ __('Hiç muafiyet kaydı yok.') }}
          </td>
        </tr>
      @elseif (!$list->count())
        <tr>
          <td class="text-center text-muted" colspan="12">
            {{ __('Lütfen sicil no ile arama yapın.') }}
          </td>
        </tr>
      @endif
    </tbody>
  </table>
</div>
@endsection