routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::get('/', 'HomeController@index')
    ->name('home')
    ->middleware('auth');
Route::resource('fee', 'FeeController')
    ->middleware('auth');
Route::resource('exemption-type', 'ExemptionTypeController')
    ->middleware('auth');
Route::resource('exemption-source', 'ExemptionSourceController')
    ->middleware('auth');
Route::resource('user', 'UserController')
    ->middleware('auth');
Route::resource('exemption', 'ExemptionController')
    ->middleware('auth');
Route::get('report', 'ReportController@index')
    ->name('report.index')
    ->middleware('auth');
Route::get('report/csv', 'ReportController@getCSV')
    ->name('report.csv')
    ->middleware('auth');

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Laravel') }}</title>

  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}" defer></script>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="//fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
  <div id="app">
    <nav class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
          {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left Side Of Navbar -->
          <ul class="navbar-nav mr-auto">
            @auth
            <li class="nav-item">
              <a class="nav-link" href="{{ route('fee.index') }}">
                {{ __('Ödentiler') }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('exemption-type.index') }}">
                {{ __('Muafiyet Türleri') }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('exemption-source.index') }}">
                {{ __('Bilgi Kaynakları') }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('user.index') }}">
                {{ __('Üyeler') }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('report.index') }}">
                {{ __('Rapor') }}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-danger" href="{{ route('exemption.index') }}">
                {{ __('Muafiyetler') }}
              </a>
            </li>
            @endauth
          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
            <li class="nav-item">
              <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item">
              <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @endif
            @else
            <li class="nav-item dropdown">
              <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
              </a>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                  {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
              </div>
            </li>
            @endguest
          </ul>
        </div>
      </div>
    </nav>

    <main class="py-4">
      @yield('content')
    </main>
  </div>

  @if(app()->environment('production') and !empty(config('app.matomo_site_id')))
    <!-- Matomo -->
    <script type="text/javascript">
      var _paq = window._paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="https://abakus.bagimsizatolye.org/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '{{ config('app.matomo_site_id') }}']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Matomo Code -->
  @endif
</body>

</html>